"use client";

import { useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import Map from "./map";

type Campsite = {
  id: string; name: string; area: string; type: string; latitude: number; longitude: number;
  cost: number | null; reservation: string; rating: number | null; favorite: boolean;
  notes: string; source: string; source_url: string; last_verified_at: string | null;
};
type Trip = { id: string; name: string; start_location: string | null; destinations: string[]; mpg: number | null; tank_gallons: number | null; fuel_reserve_percent: number; created_at: string };
type Stop = { id?: string; name: string; latitude: number; longitude: number; campsite_id?: string; stop_order: number; notes?: string };

const sampleCampsites: Campsite[] = [
  { id:"demo-1", name:"Shadow Mountain", area:"Grand Teton, WY", type:"Dispersed", latitude:43.697, longitude:-110.631, cost:0, reservation:"Dispersed / no reservation", rating:5, favorite:true, notes:"Great backup near Grand Teton.", source:"iOverlander", source_url:"", last_verified_at:"2026-08-01" },
  { id:"demo-2", name:"Madison Campground", area:"Yellowstone, WY", type:"Developed", latitude:44.645, longitude:-110.862, cost:35, reservation:"Reservation", rating:5, favorite:true, notes:"Primary Yellowstone option.", source:"Recreation.gov", source_url:"", last_verified_at:"2026-08-01" },
  { id:"demo-3", name:"Baker's Hole", area:"West Yellowstone, MT", type:"Forest campground", latitude:44.684, longitude:-111.122, cost:25, reservation:"First come / check current rules", rating:4, favorite:false, notes:"Good Yellowstone backup.", source:"Personal research", source_url:"", last_verified_at:"2026-08-01" },
  { id:"demo-4", name:"Gros Ventre Campground", area:"Grand Teton, WY", type:"Developed", latitude:43.660, longitude:-110.649, cost:25, reservation:"Varies", rating:4, favorite:false, notes:"Useful backup for the Jackson side.", source:"Recreation.gov", source_url:"", last_verified_at:"2026-08-01" },
];

export default function Home() {
  const [tab,setTab]=useState<"Dashboard"|"Trips"|"Campsites"|"Fuel"|"Budget"|"Pack List">("Dashboard");
  const [view,setView]=useState<"list"|"map">("list");
  const [userEmail,setUserEmail]=useState(""); const [authOpen,setAuthOpen]=useState(false); const [authBusy,setAuthBusy]=useState(false); const [authEmail,setAuthEmail]=useState(""); const [authPassword,setAuthPassword]=useState("");
  const [message,setMessage]=useState("");
  const [campsites,setCampsites]=useState<Campsite[]>([]); const [loadingCamps,setLoadingCamps]=useState(false);
  const [showCampForm,setShowCampForm]=useState(false); const [editing,setEditing]=useState<Campsite|null>(null); const [search,setSearch]=useState(""); const [areaFilter,setAreaFilter]=useState("All");
  const [trips,setTrips]=useState<Trip[]>([]); const [tripName,setTripName]=useState("Yellowstone Adventure"); const [start,setStart]=useState("Kansas City, MO"); const [selectedTrip,setSelectedTrip]=useState<Trip|null>(null);
  const [mpg,setMpg]=useState(15); const [tank,setTank]=useState(36); const [reserve,setReserve]=useState(15); const [stops,setStops]=useState<Stop[]>([]); const [routeLoading,setRouteLoading]=useState(false); const [route,setRoute]=useState<any>(null); const [fuelStations,setFuelStations]=useState<any[]>([]);
  const [budget,setBudget]=useState({camp:300,food:500,fees:100,other:200});
  const [pack,setPack]=useState(["Recovery boards","Air compressor","First aid kit","Headlamps","Water storage","Camp stove","Cooler","Tool kit"]);
  const [newPack,setNewPack]=useState("");

  useEffect(()=>{ const sb=createClient(); let mounted=true; sb.auth.getUser().then(({data})=>{if(mounted)setUserEmail(data.user?.email||"")}); const {data}=sb.auth.onAuthStateChange((_e,s)=>mounted&&setUserEmail(s?.user?.email||"")); return()=>{mounted=false;data.subscription.unsubscribe()}; },[]);
  useEffect(()=>{ if(userEmail) { loadCampsites(); loadTrips(); } else { setCampsites([]); setTrips([]); } },[userEmail]);

  async function loadCampsites(){setLoadingCamps(true); const sb=createClient(); const {data,error}=await sb.from("campsites").select("*").order("name"); if(error){setMessage(error.message)} else setCampsites(data||[]); setLoadingCamps(false)}
  async function loadTrips(){const sb=createClient(); const {data}=await sb.from("trips").select("id,name,start_location,destinations,mpg,tank_gallons,fuel_reserve_percent,created_at").order("created_at",{ascending:false}); setTrips(data||[])}
  async function auth(mode:"signin"|"signup"){setAuthBusy(true);setMessage("");const sb=createClient();const fn=mode==="signin"?sb.auth.signInWithPassword({email:authEmail,password:authPassword}):sb.auth.signUp({email:authEmail,password:authPassword});const {error}=await fn;if(error)setMessage(error.message);else {setMessage(mode==="signup"?"Account created. Check your email if confirmation is required.":"Signed in.");setAuthOpen(false)}setAuthBusy(false)}
  async function signOut(){await createClient().auth.signOut();setMessage("Signed out.")}

  const areas=useMemo(()=>["All",...Array.from(new Set(campsites.map(c=>c.area))).sort()],[campsites]);
  const filtered=campsites.filter(c=>`${c.name} ${c.area} ${c.type}`.toLowerCase().includes(search.toLowerCase())&&(areaFilter==="All"||c.area===areaFilter));
  const fullRange=Math.round(mpg*tank); const safeRange=Math.round(fullRange*(1-reserve/100));
  const routeStops=stops.length?stops:[];

  function openNew(){setEditing(null);setShowCampForm(true)}
  function openEdit(c:Campsite){setEditing(c);setShowCampForm(true)}
  async function saveCampsite(c:Campsite){if(!userEmail){setAuthOpen(true);return}const sb=createClient(); const payload={name:c.name,area:c.area,type:c.type,latitude:c.latitude,longitude:c.longitude,cost:c.cost,reservation:c.reservation,rating:c.rating,favorite:c.favorite,notes:c.notes,source:c.source,source_url:c.source_url,last_verified_at:c.last_verified_at||null}; const q=editing?sb.from("campsites").update(payload).eq("id",editing.id):sb.from("campsites").insert({...payload,user_id:(await sb.auth.getUser()).data.user?.id}).select().single(); const {error}=await q;if(error){setMessage(error.message);return}setShowCampForm(false);setMessage("Campsite saved.");loadCampsites()}
  async function deleteCampsite(c:Campsite){if(!confirm(`Delete ${c.name}?`))return;const {error}=await createClient().from("campsites").delete().eq("id",c.id);if(error)setMessage(error.message);else loadCampsites()}
  async function createTrip(){if(!userEmail){setAuthOpen(true);return}const sb=createClient();const {data:user}=await sb.auth.getUser();const {data,error}=await sb.from("trips").insert({user_id:user.user?.id,name:tripName,start_location:start,destinations:[],mpg,tank_gallons:tank,fuel_reserve_percent:reserve}).select().single();if(error){setMessage(error.message);return}setTrips([data,...trips]);setSelectedTrip(data);setTab("Trips");setMessage("Trip created.")}
  async function saveStops(){if(!selectedTrip)return;const sb=createClient();await sb.from("trip_stops").delete().eq("trip_id",selectedTrip.id);const {error}=await sb.from("trip_stops").insert(stops.map((s,i)=>({trip_id:selectedTrip.id,campsite_id:s.campsite_id||null,name:s.name,latitude:s.latitude,longitude:s.longitude,stop_order:i,notes:s.notes||""})));setMessage(error?error.message:"Trip stops saved.")}
  function addStop(c:Campsite){setStops(prev=>[...prev,{name:c.name,latitude:c.latitude,longitude:c.longitude,campsite_id:c.id,stop_order:prev.length}]);setTab("Trips")}
  async function calculateRoute(){if(stops.length<2){setMessage("Add at least two stops to calculate a route.");return}const token=process.env.NEXT_PUBLIC_MAPBOX_TOKEN;if(!token){setMessage("Add NEXT_PUBLIC_MAPBOX_TOKEN in Vercel to enable maps and routing.");return}setRouteLoading(true);setMessage("");const coords=stops.map(s=>`${s.longitude},${s.latitude}`).join(";");const res=await fetch(`https://api.mapbox.com/directions/v5/mapbox/driving/${coords}?geometries=geojson&overview=full&steps=false&access_token=${token}`);const data=await res.json();if(!res.ok||data.code!=="Ok"){setMessage(data.message||"Mapbox routing failed.");setRouteLoading(false);return}setRoute(data.routes?.[0]||null);const geometry=data.routes?.[0]?.geometry; if(geometry){const encoded=encodePolyline6(geometry.coordinates); const searchUrl=`https://api.mapbox.com/search/searchbox/v1/category/gas_station?route=${encodeURIComponent(encoded)}&route_geometry=polyline6&sar_type=isochrone&time_deviation=15&limit=10&access_token=${token}`; try{const fr=await fetch(searchUrl);const fd=await fr.json();setFuelStations(fd.features||[])}catch{setFuelStations([])}}setRouteLoading(false);await saveStops()}

  return <div className="app-shell">
    <header className="topbar"><div className="brand"><span className="brand-mark">↗</span><div><strong>OVERLAND PLANNER</strong><small>Trip logistics, simplified.</small></div></div><div className="top-actions">{userEmail?<><span className="user-pill">{userEmail}</span><button onClick={signOut}>Sign out</button></>:<button className="primary" onClick={()=>setAuthOpen(true)}>Sign in</button>}</div></header>
    <div className="body"><aside className="sidebar">{["Dashboard","Trips","Campsites","Fuel","Budget","Pack List"].map(x=><button key={x} className={tab===x?"nav active":"nav"} onClick={()=>setTab(x as any)}><span>{x==="Campsites"?"⌂":x==="Fuel"?"⛽":x==="Budget"?"$":x==="Pack List"?"✓":x==="Trips"?"⌁":"▦"}</span>{x}</button>)}<div className="side-note"><b>Our lane</b><span>Your campsites. Your route. Your fuel plan.</span></div></aside>
    <main className="main">
      {tab==="Dashboard"&&<Dashboard trips={trips} campsites={campsites} safeRange={safeRange} createTrip={()=>setTab("Trips")} />}
      {tab==="Trips"&&<TripsView trips={trips} tripName={tripName} setTripName={setTripName} start={start} setStart={setStart} createTrip={createTrip} selectedTrip={selectedTrip} setSelectedTrip={setSelectedTrip} campsites={campsites} addStop={addStop} stops={stops} setStops={setStops} route={route} routeLoading={routeLoading} calculateRoute={calculateRoute} fuelStations={fuelStations} saveStops={saveStops}/>} 
      {tab==="Campsites"&&<section className="content"><div className="page-head"><div><span className="eyebrow">CAMPSITE LIBRARY</span><h1>Your campsites.</h1><p>Save the places you find elsewhere. Use them as primary stops or backups on future trips.</p></div><button className="primary" onClick={openNew}>＋ Add campsite</button></div><div className="toolbar"><input placeholder="Search campsites..." value={search} onChange={e=>setSearch(e.target.value)}/><select value={areaFilter} onChange={e=>setAreaFilter(e.target.value)}>{areas.map(a=><option key={a}>{a}</option>)}</select><div className="seg"><button className={view==="list"?"selected":""} onClick={()=>setView("list")}>List</button><button className={view==="map"?"selected":""} onClick={()=>setView("map")}>Map</button></div></div>{!userEmail?<EmptyState title="Sign in to build your campsite library." action={()=>setAuthOpen(true)}/>:loadingCamps?<div className="loading">Loading campsites…</div>:view==="map"?<div className="map-card"><Map campsites={filtered} route={null} onSelect={openEdit}/></div>:<div className="table-card"><div className="table-head"><span>Campsite</span><span>Area</span><span>Type</span><span>Cost</span><span>Rating</span><span></span></div>{filtered.length?filtered.map(c=><div className="table-row" key={c.id}><div><strong>{c.favorite?"★ ":""}{c.name}</strong><small>{c.notes||"No notes yet"}</small></div><span>{c.area}</span><span>{c.type}</span><span>{c.cost==null?"—":c.cost===0?"Free":`$${c.cost}`}</span><span>{c.rating?"★".repeat(c.rating):"—"}</span><div className="row-actions"><button onClick={()=>addStop(c)}>＋ Trip</button><button onClick={()=>openEdit(c)}>Edit</button><button onClick={()=>deleteCampsite(c)}>Delete</button></div></div>):<div className="empty">No campsites match your filters.</div>}</div>}</section>}
      {tab==="Fuel"&&<FuelView mpg={mpg} setMpg={setMpg} tank={tank} setTank={setTank} reserve={reserve} setReserve={setReserve} safeRange={safeRange} fullRange={fullRange} route={route} stations={fuelStations}/>} 
      {tab==="Budget"&&<BudgetView budget={budget} setBudget={setBudget}/>} 
      {tab==="Pack List"&&<PackView pack={pack} setPack={setPack} newPack={newPack} setNewPack={setNewPack}/>} 
    </main></div>
    {showCampForm&&<CampForm initial={editing} onClose={()=>setShowCampForm(false)} onSave={saveCampsite}/>} 
    {authOpen&&<AuthModal email={authEmail} password={authPassword} setEmail={setAuthEmail} setPassword={setAuthPassword} busy={authBusy} onClose={()=>setAuthOpen(false)} onSignIn={()=>auth("signin")} onSignUp={()=>auth("signup")}/>} 
    {message&&<button className="toast" onClick={()=>setMessage("")}>{message}</button>}
  </div>
}

function Dashboard({trips,campsites,safeRange,createTrip}:any){return <section className="content"><div className="hero"><span className="eyebrow">OVERLAND PLANNER 0.6</span><h1>Plan the trip.<br/><i>Not everything else.</i></h1><p>A focused workspace for the parts of overlanding that are hardest to keep straight: campsites, routes, fuel and budget.</p><button className="primary" onClick={createTrip}>Build a trip</button></div><div className="stat-grid"><Stat n={trips.length} label="Saved trips"/><Stat n={campsites.length} label="Saved campsites"/><Stat n={`${safeRange} mi`} label="Current safe range"/></div><div className="three"><Card title="Campsite library" text="Keep your own list of primary and backup campsites, with coordinates ready for routing."/><Card title="Fuel planning" text="Route first. Then find fuel along the road and layer pricing on top."/><Card title="Simple budget" text="Keep the practical costs that matter on a long overland trip in one place."/></div></section>}
function TripsView({trips,tripName,setTripName,start,setStart,createTrip,selectedTrip,setSelectedTrip,campsites,addStop,stops,setStops,route,routeLoading,calculateRoute,fuelStations,saveStops}:any){return <section className="content"><div className="page-head"><div><span className="eyebrow">TRIPS</span><h1>Route your stops.</h1><p>Pick campsites from your library. Then let routing and fuel planning handle the logistics.</p></div></div><div className="trip-builder"><div className="form-card"><h3>New trip</h3><label>Trip name<input value={tripName} onChange={e=>setTripName(e.target.value)}/></label><label>Starting point<input value={start} onChange={e=>setStart(e.target.value)}/></label><button className="primary" onClick={createTrip}>Create trip</button></div><div className="form-card"><h3>Saved trips</h3>{trips.length?trips.map((t:Trip)=><button className={selectedTrip?.id===t.id?"trip-item selected":"trip-item"} key={t.id} onClick={()=>setSelectedTrip(t)}><strong>{t.name}</strong><small>{t.start_location||"No start"}</small></button>):<div className="empty">No saved trips yet.</div>}</div></div>{selectedTrip&&<div className="route-workspace"><div className="route-sidebar"><div className="section-title"><div><span className="eyebrow">{selectedTrip.name}</span><h2>Stops</h2></div><button onClick={saveStops}>Save</button></div>{stops.map((s:Stop,i:number)=><div className="stop-row" key={`${s.name}-${i}`}><span>{i+1}</span><div><strong>{s.name}</strong><small>{s.latitude.toFixed(4)}, {s.longitude.toFixed(4)}</small></div><button onClick={()=>setStops((p:Stop[])=>p.filter((_,idx)=>idx!==i))}>×</button></div>)}<div className="library-mini"><b>Add from library</b>{campsites.slice(0,8).map((c:Campsite)=><button key={c.id} onClick={()=>addStop(c)}>＋ {c.name}</button>)}</div><button className="primary full" disabled={routeLoading} onClick={calculateRoute}>{routeLoading?"Calculating…":"Calculate route & fuel"}</button></div><div className="route-map"><Map campsites={campsites} route={route} stops={stops} fuelStations={fuelStations}/></div></div>}</section>}
function FuelView({mpg,setMpg,tank,setTank,reserve,setReserve,safeRange,fullRange,route,stations}:any){const miles=route?Math.round(route.distance/1609.344):0;const hours=route?Math.round(route.duration/3600*10)/10:0;return <section className="content"><div className="page-head"><div><span className="eyebrow">FUEL</span><h1>Know your range.</h1><p>Vehicle assumptions stay simple. The route tells us where fuel needs to happen.</p></div></div><div className="fuel-grid"><div className="form-card"><h3>Vehicle</h3><label>MPG<input type="number" value={mpg} onChange={e=>setMpg(Number(e.target.value))}/></label><label>Tank gallons<input type="number" value={tank} onChange={e=>setTank(Number(e.target.value))}/></label><label>Reserve %<input type="number" value={reserve} onChange={e=>setReserve(Number(e.target.value))}/></label><div className="big-number">{safeRange}<small>safe miles</small></div><span className="muted">{fullRange} miles at a full tank</span></div><div className="form-card"><h3>Current route</h3>{route?<><div className="metric-line"><span>Distance</span><b>{miles.toLocaleString()} mi</b></div><div className="metric-line"><span>Drive time</span><b>{hours} hr</b></div><h4>Gas stations found along route</h4>{stations?.length?stations.slice(0,8).map((s:any)=><div className="station" key={s.properties?.mapbox_id||s.id}><div><strong>{s.properties?.name||s.text||"Gas station"}</strong><small>{s.properties?.full_address||s.properties?.place_formatted||""}</small></div><span>Price pending</span></div>):<div className="empty">No stations returned yet.</div>}<p className="muted">CollectAPI pricing will plug into these station records once the account endpoint is configured.</p></>:<div className="empty">Calculate a route from the Trips page first.</div>}</div></div></section>}
function BudgetView({budget,setBudget}:any){const total=Object.values(budget).reduce((a:any,b:any)=>a+Number(b),0);return <section className="content"><div className="page-head"><div><span className="eyebrow">BUDGET</span><h1>Keep the math simple.</h1><p>Fuel will become route-driven. Everything else stays editable.</p></div></div><div className="budget-card">{Object.entries(budget).map(([k,v]:any)=><label key={k}>{k.replace("fees","park fees").replace("camp","camping").replace("other","other").replace("food","food")}<input type="number" value={v} onChange={e=>setBudget({...budget,[k]:Number(e.target.value)})}/></label>)}<div className="total"><span>Current non-fuel budget</span><strong>${total.toLocaleString()}</strong></div></div></section>}
function PackView({pack,setPack,newPack,setNewPack}:any){return <section className="content"><div className="page-head"><div><span className="eyebrow">PACK LIST</span><h1>Reuse your loadout.</h1><p>A simple checklist. Nothing more.</p></div></div><div className="pack-card"><div className="add-row"><input placeholder="Add item" value={newPack} onChange={e=>setNewPack(e.target.value)}/><button className="primary" onClick={()=>{if(newPack.trim()){setPack([...pack,newPack.trim()]);setNewPack("")}}}>Add</button></div>{pack.map((x:string,i:number)=><label className="check" key={`${x}-${i}`}><input type="checkbox"/><span>{x}</span></label>)}</div></section>}
function CampForm({initial,onClose,onSave}:any){const blank={name:"",area:"",type:"Dispersed",latitude:"",longitude:"",cost:"",reservation:"",rating:"",favorite:false,notes:"",source:"",source_url:"",last_verified_at:""};const [f,setF]=useState<any>(initial?{...initial,latitude:String(initial.latitude),longitude:String(initial.longitude),cost:initial.cost==null?"":String(initial.cost),rating:initial.rating==null?"":String(initial.rating)}:blank);const set=(k:string,v:any)=>setF((p:any)=>({...p,[k]:v}));return <div className="modal-backdrop"><div className="modal"><div className="modal-head"><div><span className="eyebrow">CAMPSITE</span><h2>{initial?"Edit campsite":"Add campsite"}</h2></div><button onClick={onClose}>×</button></div><div className="form-grid">{[["name","Name"],["area","Area / region"],["latitude","Latitude"],["longitude","Longitude"],["cost","Cost / night"],["rating","Your rating 1–5"],["reservation","Reservation / access"],["source","Source"]].map(([k,l])=><label key={k}>{l}<input value={f[k]} onChange={e=>set(k,e.target.value)} /></label>)}</div><label>Type<select value={f.type} onChange={e=>set("type",e.target.value)}><option>Dispersed</option><option>Developed</option><option>Forest campground</option><option>Private campground</option><option>Other</option></select></label><label>Notes<textarea value={f.notes} onChange={e=>set("notes",e.target.value)} /></label><label>Source URL<input value={f.source_url} onChange={e=>set("source_url",e.target.value)} /></label><label className="check"><input type="checkbox" checked={f.favorite} onChange={e=>set("favorite",e.target.checked)}/><span>Favorite / preferred campsite</span></label><div className="modal-actions"><button onClick={onClose}>Cancel</button><button className="primary" onClick={()=>onSave({...f,latitude:Number(f.latitude),longitude:Number(f.longitude),cost:f.cost===""?null:Number(f.cost),rating:f.rating===""?null:Number(f.rating)})}>Save campsite</button></div></div></div>}
function AuthModal({email,password,setEmail,setPassword,busy,onClose,onSignIn,onSignUp}:any){return <div className="modal-backdrop"><div className="modal auth"><div className="modal-head"><div><span className="eyebrow">ACCOUNT</span><h2>Save your planner.</h2></div><button onClick={onClose}>×</button></div><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label><div className="modal-actions"><button disabled={busy} onClick={onSignIn}>Sign in</button><button className="primary" disabled={busy} onClick={onSignUp}>Create account</button></div></div></div>}
function Stat({n,label}:any){return <div className="stat"><strong>{n}</strong><span>{label}</span></div>};function Card({title,text}:any){return <div className="feature-card"><h3>{title}</h3><p>{text}</p></div>};function EmptyState({title,action}:any){return <div className="empty"><strong>{title}</strong><button onClick={action}>Sign in</button></div>}

function encodePolyline6(coords:number[][]){let lastLat=0,lastLng=0,out="";for(const [lng,lat] of coords){const lat6=Math.round(lat*1e6),lng6=Math.round(lng*1e6);out+=encodeSigned(lat6-lastLat)+encodeSigned(lng6-lastLng);lastLat=lat6;lastLng=lng6;}return out}
function encodeSigned(v:number){let n=v<0?~(v<<1):(v<<1);let s="";while(n>=0x20){s+=String.fromCharCode((0x20|(n&0x1f))+63);n>>=5}s+=String.fromCharCode(n+63);return s}
